# docker-compose.yml
version: "3.8"

services:
  wildsrincon:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:delegated
      - /node_modules
    ports:
      - 5173:5173
    environment:
      CHOKIDAR_USEPOLLING: "true"
